name: Release

on:
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 24.x
        uses: actions/setup-node@v3
        with:
          node-version: 24.x

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn test
